# SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
"""Assert that every measured figure quoted in the optimized-decoder docs exists in a committed artifact.

The same guard the two preceding stages carry (``../fused_decoder/audit_figures.py``), pointed at this
stage's documents and evidence. Review rounds 2, 3 and 4 of this stage each closed on "the figures are
re-derived" and each next round found more that were not: round 4 found eight, including a whole
program-config search table quoting a superseded run of its own probe. Round 4's finding was that the
remedy already existed one directory over and this stage had not carried it. This is that port.

Passes over every document:

* **decimals** — every ``\\d+.\\d+`` must appear in some committed evidence file;
* **integers** — every 2+ digit integer must too, minus a declared set of shape/config constants;
* **labelled figures** — ``N passed`` and friends must appear in an artifact *together with their
  label*, because a bare integer will match something by accident in a large log.

Figures computed from other figures rather than read off a run are declared in ``DERIVED`` as an
**expression**, which is evaluated and must reproduce the quoted value; every literal in the
expression must itself be sourced. That is what stops a document quoting a correct-looking ratio that
was derived from the wrong basis.

    python models/autoports/ornith_ai_ornith_1_0_35b/doc/optimized_decoder/audit_figures.py

Exit code 0 means every quoted figure traces to an artifact. Run it after any doc edit and after any
re-run that changes the numbers; ``logs/run_evidence.sh`` runs it last, in-tree and again against a
``git archive HEAD`` extraction.

**Measured strength, so a reader does not over-trust it.** Round 5 of the stage review measured what the
first version proved by asking ``sourced()`` about arbitrary values, and that experiment is worth repeating
after any change to the rules below. With the labelled-token rule and the per-op reports excluded:

``logs/audit_selftest.txt`` carries the current rates, written by ``--selftest`` and regenerated by
``run_evidence.sh``, so they are an artifact rather than a claim in this docstring. At the time of writing:
millisecond figures and byte counts are well guarded (about 1 in 70 and 0 in 2000), six-decimal PCCs
likewise, and **one-decimal microsecond figures are the residual weakness** at roughly one in five. The
substring rule this replaced scored about 4 in 5 on the millisecond class, which is what round 5 measured.

That residual weakness is inherent — the probes legitimately print hundreds of distinct
one-decimal microsecond values, so a wrong one has a real chance of colliding with a right one. The
paragraph-scoped citation check is what narrows that in practice: a figure in a paragraph that names its log
is checked against that log alone, a few kilobytes rather than everything.

Two things this cannot do at all: it checks figures, not prose, so it cannot tell that a *correct* number is
being used to support a wrong claim; and it cannot see a figure that is simply absent.
"""

from __future__ import annotations

import gzip
import hashlib
import re
import subprocess
import sys
from pathlib import Path

DOC = Path(__file__).resolve().parent
ROOT = DOC.parent.parent
#: The tt-metal checkout, so generator subprocesses and error messages are repo-relative.
REPO = ROOT.parents[1]
FUSED = DOC.parent / "fused_decoder"
CONTRACT = DOC.parent / "context_contract.json"

#: The implementation and the tests the artifacts below measure. Two rules apply to them: figures
#: quoted in their comments must be sourced like any other document's, and every artifact must be
#: **newer** than all of them — otherwise the evidence describes an earlier revision of the code being
#: shipped. Round 4 flagged exactly that gap: a 50-line edit landed after six of the probe artifacts.
SOURCES = [
    ROOT / "tt/optimized_decoder.py",
    ROOT / "tests/test_optimized_decoder.py",
    ROOT / "tests/conftest.py",
]

#: Documents whose figures must be sourced. ``logs/make_readme.py`` is here because its
#: ``ADVICE_ACTIONS`` prose carries measured microsecond figures into the README's *generated* advice
#: block — so ``make_readme.py --check`` agrees with itself while quoting a stale number, which is
#: precisely how three of round 4's eight findings survived three rounds of review.
DOCS = [
    CONTRACT,
    DOC / "README.md",
    DOC / "work_log.md",
    DOC / "watcher/CLASSIFICATION.md",
    DOC / "logs/make_readme.py",
    # The probe and harness scripts too: their module docstrings quote measured figures to explain why
    # the probe exists, and one of them was still quoting a pre-round-4 pair of percentages that no
    # artifact contained. A script is a document when it makes a claim about a measurement.
    *sorted(DOC.glob("logs/probe_*.py")),
    DOC / "logs/ab_norm_shard_cores.py",
    DOC / "logs/ab_gate_up_in0_block_w.py",
    DOC / "logs/ab_decode_harness.py",
    DOC / "logs/ab_sdpa_decode_grid.py",
    DOC / "logs/ab_routed_in0.py",
    DOC / "logs/model_facts.py",
    DOC / "logs/bench.py",
    DOC / "tracy/perf_accounting.py",
    DOC / "watcher/census.py",
    # The two hand-written harness scripts. They quote artifact sizes and thresholds rather than
    # measurements today, but they are stage documents that make claims, and leaving them out left a route
    # for a figure to be quoted in a file nothing checks.
    DOC / "logs/run_evidence.sh",
    DOC / "tracy/run_profiling.sh",
    *SOURCES,
]

#: Evidence a **hand-written** figure may come from: the structured logs, where every measurement is
#: printed as a labelled field (``us=``, ``wall/iter=… ms``, ``pcc=``, ``bytes=``, a JSON key, a census
#: count). ``read_blob`` below reads ``x`` or ``x.gz``, because the repo's 500 KB file-size hook and its
#: blanket ``*.csv`` ignore rule mean the large artifacts are committed gzipped.
#:
#: The per-op ``tt-perf-report`` tables and CSVs are deliberately **NOT** here, and that is the single
#: most important decision in this file. Round 5 of the stage review measured what the previous version of
#: this audit actually proved, by asking ``sourced()`` about arbitrary values: with those multi-megabyte
#: per-op reports in the pool, **794 of 2000** arbitrary one-decimal values and **1581 of 2000** arbitrary
#: three-decimal values in 0..10 came back "sourced" - a per-op report is a dense soup of thousands of
#: durations, so almost any plausible microsecond or millisecond figure appears in it somewhere by
#: coincidence. For the two figure classes that were rounds 2-4's actual findings, the check was close to a
#: no-op while the README advertised it as the reason those findings could not recur.
#:
#: So: prose figures must be sourced by a *labelled* measurement (see ``measured_tokens``), and the per-op
#: reports reach the documents only through a generated block, whose correctness ``make_readme.py --check``
#: establishes separately. ``PER_OP_REPORTS`` below is still checked for existence and freshness - it is
#: evidence, it just is not evidence that a hand-typed number is right.
ARTIFACTS = [
    DOC / "logs/pytest_full_suite.txt",
    DOC / "logs/watcher_pytest.txt",
    DOC / "logs/commit_record.txt",
    DOC / "logs/source_manifest.txt",
    DOC / "logs/model_facts.txt",
    DOC / "logs/ab_fused_vs_optimized.txt",
    DOC / "logs/ab_precision_policy.txt",
    DOC / "logs/ab_norm_shard_width.txt",
    DOC / "logs/ab_norm_shard_cores.txt",
    DOC / "logs/ab_gate_up_in0_block_w.txt",
    DOC / "logs/ab_decode_harness.txt",
    DOC / "logs/ab_sdpa_decode_grid.txt",
    DOC / "logs/ab_state_l1.txt",
    DOC / "logs/ab_sdpa_decode_contract.txt",
    DOC / "logs/ab_gdn_out_activation.txt",
    DOC / "logs/probe_sparse_matmul.txt",
    DOC / "logs/probe_prefill_sdpa.txt",
    DOC / "logs/ab_routed_in0.txt",
    DOC / "logs/probe_dense_matmul.txt",
    DOC / "logs/probe_prefill_matmul.txt",
    DOC / "logs/probe_decode_micro.txt",
    DOC / "logs/probe_projection_dtype.txt",
    DOC / "logs/probe_footprint.txt",
    DOC / "tracy/perf_summary.json",
    DOC / "tracy/perf_accounting.txt",
    DOC / "watcher/census_summary.txt",
    DOC / "watcher/watcher_log.txt",
    DOC / "triage/tt-triage.txt",
    DOC / "triage/triage-summary.txt",
    CONTRACT,
    *sorted((DOC / "tracy").glob("*/*_tracy_run.txt")),
    # The fused decoder is this stage's measured baseline, so its evidence is evidence here.
    FUSED / "tracy/perf_summary.txt",
    FUSED / "tracy/derived_figures.txt",
    FUSED / "tracy/fill_summary.txt",
    FUSED / "tracy/slow_ops_summary.txt",
    FUSED / "logs/pcc_summary.txt",
    FUSED / "logs/probe_decode_micro.txt",
    FUSED / "logs/probe_router_and_reduce.txt",
    FUSED / "logs/probe_fused_ops.txt",
    FUSED / "logs/probe_conv1d_and_norm.txt",
    FUSED / "logs/ab_moe_group_tokens.txt",
    DOC.parent / "functional_decoder/logs/dram_capacity_probe.txt",
    DOC.parent / "functional_decoder/logs/router_precision_ab.txt",
]

#: The per-op reports and CSVs: required to exist, required to be fresh, and excluded from the
#: hand-figure sourcing pool for the reason given above.
PER_OP_REPORTS = [
    *sorted((DOC / "tracy").glob("*/*_perf_report.txt")),
    *sorted((DOC / "tracy").glob("*/*_perf_report.txt.gz")),
    *sorted((DOC / "tracy").glob("*/*_perf_report.summary.txt")),
    *sorted((DOC / "tracy").glob("*/*_perf_report.summary.txt.gz")),
    *sorted((DOC / "tracy").glob("*/*_perf_report.csv")),
    *sorted((DOC / "tracy").glob("*/*_perf_report.csv.gz")),
]

#: Values computed from sourced numbers rather than measured. Each maps the quoted string to
#: ``(expression, what it is)``; the expression is evaluated and must reproduce the quoted value at the
#: precision it is quoted, and every literal in it must itself be sourced.
DERIVED: dict[str, tuple[str, str]] = {
    # Every per-term byte count in context_contract.json's optimized-decoder footprint section is now
    # MEASURED by logs/probe_footprint.py and sourced from its artifact, so it does not need an
    # expression here. What remains is the arithmetic the contract states about shapes the probe cannot
    # see, and the one capacity figure that comes from an earlier stage's probe.
    #
    # bfloat8_b is 1.0625 B/elem and bfloat4_b 0.5625 B/elem (one shared exponent byte per 16-datum
    # face); hidden 2048, moe_intermediate 512, 256 experts, head_dim 256, 2 kv heads, context 262144
    # in 64-token blocks.
    "142606336": ("(262144 // 64) * 2 * 64 * 256 * 1.0625", "paged K (or V) cache at BFP8, full context, B"),
    "268435456": ("(262144 // 64) * 2 * 64 * 256 * 2", "paged K (or V) cache at bfloat16, full context, B"),
    "452984832": ("3 * 256 * 2048 * 512 * 0.5625", "routed expert gate/up/down weights at BFP4, B"),
    "1610612736": ("3 * 256 * 2048 * 512 * 2", "routed expert gate/up/down weights at bfloat16, B"),
    "4460544": (
        "(2048 * 1056 + 512 * 2048) * 1.0625 + 2048 * 256 * 2",
        "shared expert at BFP8 + the bfloat16 router, B",
    ),
    "67633152": ("2 * 264192 * 64 * 2", "rope_dim-wide cos/sin tables, B"),
    "264192": ("262144 + 2048", "RoPE table rows: the context plus one prefill chunk of headroom"),
    "34091302912": ("31.75 * 1024 ** 3", "measured allocatable DRAM, B"),
    # No entry for the hand-modelled footprint's error any more: its expression subtracted a *superseded*
    # contract value that appears in no artifact and was only tolerated by ALLOWED_INT, so the audit was
    # standing in for the evidence. Review round 11 flagged it; the contract now states that error
    # qualitatively, which is all a superseded model deserves.
    # The *logical* size of the batch-1 DeltaNet conv state, which the contract quotes beside the
    # allocated padded size to explain the difference: 3 kernel-1 rows of conv_dim 8192 at bfloat16.
    "49152": ("3 * 8192 * 2", "DeltaNet conv state at batch 1, logical (unpadded), B"),
    # MATMUL_CB_MODEL_OVERHEAD's calibration: how far the modelled circular-buffer total fell short of the
    # one geometry known to fail. Both operands come from a one-off build-error message and are quoted in
    # the comment that calibrates against them; they are not measurements of a run, so they cannot drift.
    "4.3": ("100 * (1684416 - 1614848) / 1614848", "modelled CB total vs the build's own figure, % low"),
    "0.78": ("839553028 / 1024 ** 3", "worst-case optimized full_attention layer, GiB"),
    "2.12": ("2277408772 / 1024 ** 3", "worst-case fused-parity full_attention layer, GiB"),
    # The num_experts-wide MoE intermediates at bfloat16, one 32-row group: 256 experts x 32 rows x the
    # tensor's width x 2 B. gate/up is 2 x moe_intermediate wide, the down output is hidden wide.
    "16.8": ("256 * 32 * 2 * 512 * 2 / 1000 ** 2", "packed gate/up intermediate at bfloat16, MB"),
    "33.6": ("256 * 32 * 2048 * 2 / 1000 ** 2", "expert down output at bfloat16, MB"),
    # NOTE: the headline speedup ratios used to live here as expressions over *hardcoded* millisecond
    # operands, and every re-measurement made those operands vanish from the artifacts — the exact disease
    # this file exists to catch, reproduced inside the file itself. They are computed from the A/B artifact
    # at audit time now; see `derived_from_artifacts`.
}

#: Constants and thresholds that are choices, not measurements.
ALLOWED = {
    "0.995",  # the PCC acceptance bar, inherited from the functional stage
    "0.998",  # the optimized-vs-fused equivalence bar
    "0.9999",
    "0.999",
    "1.0",
    "0.25",  # partial_rotary_factor
    "1.2",  # tt-perf-report major.minor in "1.2.8"
    "3.5",  # "Qwen3.5"
    "1.0.35",  # part of the model name
    "2.0",
    "20.0",  # the SOFTPLUS threshold in UnaryWithParam(SOFTPLUS, 1.0, 20.0)
    "1.0625",  # bfloat8_b bytes per element (shared exponent per 16-datum face)
    "0.5625",  # bfloat4_b bytes per element
    # The two spaced mathematical exponents in the implementation's prose (`head_k_dim ** -0.5`,
    # `K**-0.5`), exempted by value because no whitespace rule can tell a spaced exponent from a markdown
    # bold marker — see IDENTIFIER. Both are algorithm constants: the DeltaNet key scale.
    "0.5",
    "0.1",  # activation/weight init scale in the probes
    "0.32",  # EXPERT_L1_BUDGET_FRACTION
    "0.05",  # a tolerance in make_readme.py's range formatting
    "0.0",  # a numeric default in perf_accounting.py
    "0.02",  # activation init scale in the probes
    "0.01",  # an assertion tolerance in the tests
    "100.0",  # percent conversion in perf_accounting.py
    # Accuracy targets quoted from an UPSTREAM op's own documentation (unified_routed_expert_moe's
    # nanobind docstring), not measurements this stage made.
    "0.97",
    "0.98",
    "1.05",  # MATMUL_CB_MODEL_OVERHEAD
}

#: Integers that are architecture/config/shape constants, section/round numbers or prose numbers
#: rather than measured results.
ALLOWED_INT = {
    # model + device shape constants
    "10",
    "11",
    "16",
    "24",
    "32",
    "33",
    "48",
    "55",
    "56",
    "64",
    "80",
    "88",
    "96",
    "99",
    "110",
    "128",
    "129",
    "162",
    "192",
    "250",
    "256",
    "320",
    "512",
    "1024",
    "1056",
    "2048",
    "2049",
    "3000",
    "4096",
    "5120",
    "8192",
    "9216",
    "12352",
    "16384",
    "24576",
    "32768",
    "50000",
    "65536",
    "262143",
    "262144",
    # small integers used as counts, section numbers, review-round numbers and prose
    *(str(n) for n in range(12, 100)),
    "100",
    "130",
    "200",
    "300",
    "1000",
    "1500",
    "2026",
    "1e-6",
    "1e-5",
    # Committed-artifact byte/KB sizes quoted in prose about the repo's file-size rules. Facts about
    # files, checkable with `stat`, not measurements of the model.
    "477 600",
    "477600",
    "500",
    "620",
    "720",
    "860",
    # An upstream issue number, not a measurement: tt-metal #45943, cited by the sparse_matmul factory
    # itself at its `batch_nnz` runtime argument.
    "45943",
    # Constants of the harness scripts themselves: the repo's 500 KB file-size limit and the sparse probe's
    # `--active` ladder. Choices, not measurements.
    "500000",
    "64 162",
    # The two byte counts of that build-error message, for the same reason.
    "1684416",
    "1614848",
    "1 684 416",
    "1 614 848",
    # Byte counts the contract quotes for the FUSED policy, to say what each term was before. They are
    # either in DERIVED or measured by probe_footprint.py's `fused-parity` rows; these two are the
    # earlier hand-modelled values kept in a note and are exempt as such.
}

#: A ``<!-- generated:NAME -->`` … ``<!-- /generated:NAME -->`` region of the README. Stripped before
#: scanning, because those regions are not hand-written: ``make_readme.py --check`` (run by
#: ``check_generators`` below) already proves the README equals what the generators produce from the
#: artifacts, and the generators derive figures — a per-step cost is a committed total divided by the
#: replay count, so the quotient is correct but is not a substring of any artifact. What this audit is
#: for is the prose *around* those blocks, which no generator owns. ``logs/make_readme.py`` is itself in
#: ``DOCS``, so a figure typed by hand into a generator's prose is still caught.
GENERATED_BLOCK = re.compile(r"<!-- generated:[a-z0-9-]+ -->.*?<!-- /generated:[a-z0-9-]+ -->", re.S)

#: Document *structure* rather than figures: markdown headings ("## 4. …", "### 4.11 …") and
#: cross-references ("§4.11", "§5.3"). Stripped before scanning, because a section number is not a
#: measurement and exempting each one by value would also exempt a real figure with those digits.
#: Also matches the spelled-out form ("section 4.15", "§4.15"), because a section reference is a reference
#: however it is written and a shell comment cannot type "§" portably.
SECTION = re.compile(r"(?m)^#{1,6}\s+\d+(?:\.\d+)*\.?\s|§\s?\d+(?:\.\d+)*|\bsection\s+\d+(?:\.\d+)*", re.IGNORECASE)

#: RNG seeds, source line references and git object names. All are identifiers, not measurements.
#: Rule and issue identifiers from the skills and trackers — ``OPT-013``, ``tt-metal #45943`` — which are
#: names, not measurements. Stripped for the same reason as section numbers.
RULE_ID = re.compile(r"\bOPT-\d+|#\d{4,6}\b")

IDENTIFIER = re.compile(
    # A mathematical exponent with NO space around the `**`, e.g. `head_dim**-0.5`. Safe because markdown
    # bold never has a word character immediately before its opener AND a number immediately after.
    #
    # The *spaced* form (`head_k_dim ** -0.5`) is deliberately NOT matched here. Three attempts to separate
    # it from markdown bold by regex all leaked, each in a different direction:
    #   1. `\*\*\s*-?[\d.]+` matched the bold **opener**, stripping the number of every bolded figure —
    #      which is how nearly all figures in these documents are written (round 6).
    #   2. `\w\s*\*\*…` did not help: `and **1.07 %**` has a word character before the `**` too.
    #   3. `\*\*\s+-?[\d.]+` matched after a bold **closer**: `is **taken** 777.7 us` (round 7).
    # A bold closer followed by a figure is ordinary prose, so there is no whitespace rule that separates
    # the two. The spaced exponents are therefore exempted BY VALUE in ``ALLOWED`` instead — there are two
    # of them and they are constants of the algorithm, not measurements.
    # The minus sign is required, not optional: `\w\*\*-?…` also matched `x**888.8`, i.e. a bold figure
    # immediately after an identifier (round 7). Every exponent in these documents is negative — it is the
    # DeltaNet key scale — so requiring the sign closes that without exempting anything real.
    r"\w\*\*-[\d.]+"
    r"|(?:manual_)?seed\s*[=(]\s*\d+|\bseed=\d+|\.(?:cpp|hpp|py|cc|h|sh|json|md|txt|csv):\d+(?:-\d+)?"
    # Only the EXPONENT of scientific notation, not the mantissa. The exponent has to go — otherwise the
    # `00` of "0.000e+00" reads as an integer — but stripping the whole literal exempted hand-written
    # values like "7.7e-03" from being checked at all, which round 7 flagged. This leaves the mantissa in
    # the text, where the decimal pass checks it like any other figure.
    r"|(?<=[\d.])e[+-]?\d+"
    # A git object name, which must contain at least one hex LETTER: `[0-9a-f]{7,40}` on its own also
    # matches a long decimal, which would silently exempt every byte count in the contract.
    r"|\b(?=[0-9a-f]{7,40}\b)[0-9a-f]*[a-f][0-9a-f]*\b"
)

DECIMAL = re.compile(r"(?<![\d.])\d{1,12}\.\d{1,6}(?!\.?\d)")
#: A 2+ digit integer, including one written with thin/space thousands separators ("477 600"), which the
#: documents use for byte counts. Without the separator branch this matched "477" and "600" as two
#: unrelated figures and demanded a source for each.
INTEGER = re.compile(r"(?<![\d.\w])\d{1,3}(?: \d{3})+(?!\.?\d)(?!\w)|(?<![\d.\w])\d{2,}(?!\.?\d)(?!\w)")

LABELLED = [
    (re.compile(r"(\d[\d ,]*) passed"), "{} passed"),
    (re.compile(r"(\d[\d ,]*) lines of the watcher"), "{}  TOTAL"),
    (re.compile(r"\*\*(\d[\d ,]*) matches\*\*"), "fatal-class matches: {}"),
]

#: Figures a document quotes because they belong to a *superseded* measurement round — the intermediate
#: A/B numbers that show how the graph evolved, and the wrong values a review round found. They have no
#: artifact by construction, so they are permitted only in ``work_log.md``, which is where this stage
#: records what each review round found.
#: The ``## N.`` sections of work_log.md where a superseded figure may be quoted: the development ladder and
#: the review rounds. Anywhere else in the file, a HISTORICAL value is a live claim and must be sourced.
HISTORICAL_SECTIONS = {"3", "6"}

HISTORICAL = {
    # --- Group 0: worked examples of a defect, quoted from the artifact that HAD it ----------------
    # Round 9's float-noise finding is only legible with the two operands that produced it: the sparse
    # search table printed "+0.8 us ... beyond the +-0.8 us spread" because 388.2 - 387.4 is 0.8000000000000114
    # in binary. Both operands come from the probe *run of that round*, which the next sweep replaced, so no
    # current artifact can contain them - and the pair is the evidence for a fix in the generator, not a claim
    # about today's hardware. Work log only, like every other entry here.
    "387.4",
    "388.2",
    # --- Group 1: the development ladder in work_log §3 -------------------------------------------
    # One row per change, cumulative, from one harness during development. These are measurements of
    # *intermediate revisions of the code*, so by construction no artifact of the shipped revision can
    # contain them and re-running cannot reproduce them - the intermediate states no longer exist. They
    # are the record of the path taken, they are quoted only in the work log, and the section says so.
    # The SHIPPED level is README §5.2's generated table, always.
    # Rows 15-17 of §3's ladder: the traced-decode level at three intermediate revisions. 0.849 and 1.061 were
    # the shipped values until review round 14's folds and round 15's hoist moved them, so no artifact of the
    # shipped code contains them any more - which is what this list is for.
    "0.849",
    "1.061",
    "1.044",
    "1.987",
    "1.691",
    "1.909",
    "1.624",
    "1.842",
    "1.297",
    "1.515",
    "1.253",
    "1.473",
    "0.976",
    "1.198",
    "0.983",
    "1.205",
    "0.875",
    "1.111",
    "0.855",
    "1.093",
    "1.094",
    "1.074",
    "243.44",
    "96.89",
    "257.73",
    "102.94",
    # The fused stage's published decode figure against this stage's re-measurement of the same
    # baseline, and the speedup that would follow from it. Quoted in §3 to say where the column starts.
    "2.06",
    "2.07",
    "1.86",
    # Step 15 of the ladder: the decode figures of the revision immediately before round 6's in0_block_w
    # change, quoted in §3 and §4.15 as the "before" of that step. The shipped level is README §5.2's.
    "0.858",
    "1.071",
    # Round 5's own record in §6: the row counts of the internally-inconsistent sparse artifact that a
    # re-run replaced, and the 1 MiB-fallback L1 budget round 1 found. Facts about superseded states.
    "1888",
    "472",
    # The fabricated values round 6 and round 7 injected to prove the gate was leaking. Quoted in §6 to
    # record what the experiment was; they describe a test of the checker, not a measurement of the model.
    "777.7",
    "888.8",
    # Round 5's measurement of the SUPERSEDED substring rule's false-positive rate. A fact about a checker
    # that no longer exists; `logs/audit_selftest.txt` carries the current rule's rates.
    "1581",
    "794",
    "38.5",
    "58.9",
    # --- Group 2: figures a review round found WRONG -----------------------------------------------
    # Quoted in §6 to record what each finding was. They must never come back as a claim about a run.
    "21.4",
    "9.3",
    "20.4",
    "212.1",
    "288.3",
    "134.4",
    "119.5",
    "17.1",
    "262",
    "291",
    "528.5",
    "471.9",
    "260.3",
    "178.8",
    "695.3",
    "607.0",
    "111.9",
    "64.9",
    "73.4",
    "52.6",
    "1.093",
    "1.073",
    "0.859",
    "0.839",
    "1004.7",
    "13.9",
    "12.6",
    "52.4",
    "717.4",
    "150.0",
    "14.9",
    "2.063",
    "96.61",
    "102.62",
    "243.58",
    "257.67",
    "81.65",
    "1.07",
}


def read_blob(path: Path) -> str | None:
    """Text of ``path``, or of ``path.gz``. Returns ``None`` if neither exists.

    A ``.gz`` path is decompressed rather than read as text: the glob patterns above match both
    spellings, and reading compressed bytes with ``errors="replace"`` would add a few kilobytes of
    mojibake to the evidence pool, where it could "source" a figure by coincidence.
    """
    if path.suffix == ".gz":
        return gzip.decompress(path.read_bytes()).decode(errors="replace") if path.is_file() else None
    if path.is_file():
        return path.read_text(errors="replace")
    packed = path.with_suffix(path.suffix + ".gz")
    if packed.is_file():
        return gzip.decompress(packed.read_bytes()).decode(errors="replace")
    return None


def exists(path: Path) -> bool:
    return path.is_file() or (path.suffix != ".gz" and path.with_suffix(path.suffix + ".gz").is_file())


def artifact_path(path: Path) -> Path:
    """The file that actually holds ``path``'s bytes — itself or its ``.gz``."""
    return path if path.is_file() else path.with_suffix(path.suffix + ".gz")


def load(paths) -> dict:
    blobs = {}
    for path in paths:
        body = read_blob(path)
        if body is not None:
            blobs[path] = body
    return blobs


#: Every way a committed artifact prints a *measurement*, as a regex whose only group is the value.
#: A figure is "sourced" when it equals one of these captured values exactly — not when its digits happen
#: to occur somewhere in a large file. That distinction is the whole strength of this audit: round 5
#: measured the substring version admitting ~4 in 5 arbitrary millisecond values.
MEASURED = [
    # `key=value` fields, which is how every probe and A/B log prints its numbers.
    re.compile(r"(?:^|\s)[a-zA-Z_][\w/.]*=(-?[\d.]+)"),
    # "123.4 us", "1.069 ms", "512.0 GB/s", "8192 B", "13.3 %", "1332 bytes free"
    # "123.4 us", "1.069 ms", "512.0 GB/s", "8192 B", "13.3 %", "(95.5%)", "1332 bytes free".
    # A lookahead, not `\b`: a unit is often followed by `)` or `,`, and `%\b` never matches at all.
    re.compile(r"(-?[\d.]+)\s*(?:us|µs|μs|ms|GB/s|B|%|bytes)(?![\w.])"),
    # JSON numbers, including the nested per-term byte counts of the capability contract.
    re.compile(r'":\s*(-?[\d.]+)'),
    # A census/pytest count: "  65520  TOTAL", "109 passed", "fatal-class matches: 0"
    re.compile(r"(?:^|\s)(\d[\d,]*)\s+(?:TOTAL|passed|failed|deselected|lines?)\b"),
    re.compile(r":\s*(\d+)\s*$"),
    # A markdown/table cell or bare column in a summarised report: "| 0.86 |", "  9.5   "
    re.compile(r"(?:^|[|\s])(-?\d+\.?\d*)(?=[|\s]|$)"),
]


def measured_tokens(blobs) -> set:
    """Every value any artifact prints as a labelled measurement, as a set of exact strings.

    Built once. Membership is an exact string test, so ``1.07`` is **not** sourced by ``1.075`` — the
    prefix match that admitted a wrong prefill percentage in round 5 — and a figure must appear as a
    field value rather than anywhere in a megabyte of per-op rows.
    """
    tokens = set()
    for text in blobs.values():
        for pattern in MEASURED:
            for hit in pattern.findall(text):
                tokens.add(hit)
                tokens.add(hit.replace(",", ""))
                # A document may quote a high-precision measurement truncated (0.9994 for 0.999409), so
                # prefixes are registered too - but only for values with 4+ decimals, i.e. the PCC class.
                # Doing it for timings would register 153.2 for 153.24 and widen the space of accidental
                # matches in exactly the class that is already the weakest.
                whole, _, frac = hit.partition(".")
                # ONLY for the high-precision class, i.e. 5+ decimals, which in these artifacts means a
                # PCC printed at full float precision. A document legitimately quotes
                # `PCC 0.33426908677698386` as "0.33", so those truncations are registered.
                #
                # NOT for 3-decimal timings, and that boundary matters: with a 4-decimal threshold, the
                # millisecond figure `1.075` registered the token `1.07`, which made a *wrong* prefill
                # percentage of "1.07 %" look sourced - the precise false positive round 5 caught in the
                # substring version. Every log here prints timings with at most 3 decimals, so 5 excludes
                # the whole timing class by construction rather than by luck.
                if len(frac) >= 5:
                    for cut in range(2, len(frac)):
                        tokens.add(f"{whole}.{frac[:cut]}")
    return tokens


#: An artifact filename mentioned in prose, e.g. ``probe_decode_micro.txt`` or ``ab_state_l1.txt``.
CITATION = re.compile(r"\b([a-z0-9_]+\.(?:txt|json|csv|md|py|sh))\b")


def scoped_tokens(paragraph: str, blobs, cache: dict):
    """The token set a paragraph's figures must come from.

    If the paragraph **names an artifact**, its figures must appear in *that* artifact — which is what
    "the numbers agree with the log they cite" actually means, and what round 5 asked for. Only a
    paragraph that cites nothing falls back to the whole pool. Most of this stage's prose cites its
    artifact, so most figures are checked against one file of a few kilobytes rather than against
    everything.
    """
    named = {n for n in CITATION.findall(paragraph)}
    if not named:
        return None  # caller uses the global pool
    scope = {path: body for path, body in blobs.items() if path.name in named or path.name.removesuffix(".gz") in named}
    if not scope:
        return None  # cites something that is not an artifact of this stage (a source file, a skill)
    key = tuple(sorted(p.name for p in scope))
    if key not in cache:
        cache[key] = measured_tokens(scope)
    return cache[key]


def sourced(value: str, tokens) -> bool:
    plain = value.replace(",", "").replace(" ", "")
    return value in tokens or plain in tokens


def phrase_in_artifacts(phrase: str, blobs) -> bool:
    """Substring test for a value quoted **with its label** (``109 passed``, ``fatal-class matches: 0``).

    Substring is the right test here and not for bare numbers: the label is what makes the match mean
    something, so there is no collision problem to solve.
    """
    for text in blobs.values():
        if phrase in text:
            return True
    return False


def derived_from_artifacts(blobs) -> set:
    """Tokens for figures a document may quote that are *ratios of* measured values.

    Computed here rather than declared in ``DERIVED``, because a declared expression has to name its
    operands and a measured operand changes on every run — which is how four of this audit's own entries
    went stale the first time the evidence was regenerated under them. A ratio is registered at the
    precisions a document might reasonably quote it (``2.53``, ``2.5``).
    """
    tokens: set = set()
    ab = next((body for path, body in blobs.items() if path.name == "ab_fused_vs_optimized.txt"), "")
    rows: dict = {}
    for line in ab.splitlines():
        m = re.search(r"tag=(\S+) layer=\d+ \((\w+)\) (prefill|decode)", line)
        v = re.search(r"wall(?:/iter)?=([0-9.]+) ms", line)
        if m and v:
            rows[(m.group(1), m.group(2), m.group(3))] = float(v.group(1))
    for kind in ("linear_attention", "full_attention"):
        for phase in ("prefill", "decode"):
            before, after = rows.get(("before", kind, phase)), rows.get(("after", kind, phase))
            if not before or not after:
                continue
            ratio = before / after
            for digits in (1, 2):
                tokens.add(f"{ratio:.{digits}f}")
            # The percentage reduction the README's generated table also prints.
            tokens.add(f"{100 * (1 - after / before):.1f}")
    return tokens


def check_derived(tokens) -> list:
    problems = []
    for quoted, (expression, label) in DERIVED.items():
        for literal in DECIMAL.findall(expression) + INTEGER.findall(expression):
            if literal in ALLOWED or literal in ALLOWED_INT or literal in DERIVED or sourced(literal, tokens):
                continue
            problems.append(f"DERIVED-OPERAND-UNSOURCED  {quoted} ({label}): {literal}")
        got = eval(expression)  # noqa: S307 - the table is source, not input
        digits = len(quoted.split(".")[1]) if "." in quoted else 0
        if f"{got:.{digits}f}" != quoted:
            problems.append(f"DERIVED-MISMATCH  {quoted} ({label}): {expression} = {got:.{digits + 2}f}")
    return problems


def check_source_manifest() -> list:
    """The recorded source hashes must match the files being shipped.

    Stronger than the mtime ordering below and immune to a ``touch``: ``run_evidence.sh`` records
    ``sha256sum`` of the implementation and the tests before it runs anything, so this proves the
    artifacts were produced by *these bytes*, not merely at a later wall-clock time. Round 4's
    hard-check gap was exactly this: six probe artifacts predated a source edit and nothing proved
    whether the edit was inert.
    """
    manifest = DOC / "logs/source_manifest.txt"
    if not manifest.is_file():
        return ["MISSING-ARTIFACT  logs/source_manifest.txt (run logs/run_evidence.sh)"]
    recorded = {}
    for line in manifest.read_text().splitlines():
        if line.strip() and not line.startswith("#"):
            digest, _, path = line.partition("  ")
            recorded[Path(path.strip()).name] = digest.strip()
    problems = []
    for source in SOURCES:
        if not source.is_file():
            continue
        actual = hashlib.sha256(source.read_bytes()).hexdigest()
        if recorded.get(source.name) != actual:
            problems.append(f"SOURCE-CHANGED  {source.name} differs from the manifest the evidence was produced with")
    return problems


def check_generators() -> list:
    """Every generator must reproduce exactly what is committed.

    Every generator is invoked in its **read-only** compare mode, and the bytes of its output are snapshotted
    before and compared after. Both halves matter and both came from findings: round 6 corrupted
    ``perf_summary.json``, regenerated the README from it and watched this audit report zero problems, which is
    why the outputs are diffed at all; round 13 pointed out that invoking the two summary generators in *write*
    mode meant this function repaired the drift it reported, so only the first run of a fresh clone could see it.
    Read-only makes the exit code the signal, and the snapshot proves ``--check`` did not write.
    """
    problems = []
    checks = [
        (DOC / "logs/make_readme.py", ["--check"], []),
        # `--check` rather than a bare run: both scripts gained a read-only compare mode (rounds 10 and 12), and
        # review round 13 pointed out that running them in WRITE mode means the audit repairs the very drift it
        # reports, so a second invocation passes against a mutated tree. Read-only means the exit code is the
        # signal and the snapshot below additionally proves `--check` wrote nothing.
        (DOC / "tracy/perf_accounting.py", ["--check"], [DOC / "tracy/perf_summary.json"]),
        (DOC / "watcher/census.py", ["--check"], [DOC / "watcher/census_summary.txt"]),
        # The audit's own selftest, reproducible now that its artifact is out of the evidence pool, so it is
        # diffed like any other generated summary. Round 6 found it neither regenerated by
        # `run_evidence.sh` nor checked by anything, which left "a rate that rises means the matching rules
        # got weaker" as an aspiration.
        (DOC / "audit_figures.py", ["--selftest"], [DOC / "logs/audit_selftest.txt"]),
    ]
    for script, extra, outputs in checks:
        if not script.is_file():
            problems.append(f"MISSING-SCRIPT  {script.relative_to(DOC)}")
            continue
        before = {path: path.read_bytes() for path in outputs if path.is_file()}
        result = subprocess.run([sys.executable, str(script), *extra], capture_output=True, text=True, cwd=str(REPO))
        if result.returncode:
            problems.append(f"GENERATOR-FAILED  {script.name}")
            problems += [f"    {ln}" for ln in (result.stdout + result.stderr).strip().splitlines()[-6:]]
        for path, original in before.items():
            if path.read_bytes() != original:
                problems.append(
                    f"GENERATOR-DRIFT  {script.name} rewrote {path.name} with content that differs from "
                    f"the committed version - the committed artifact is not what its generator produces"
                )
    return problems


#: Advisory findings: printed, never fatal. Today only the mtime pass produces them — a source newer than
#: the artifacts whose bytes still hash to the manifest is a touch, not stale evidence, and the manifest is
#: the stronger statement.
NOTES: list = []


def check_freshness_exemptions() -> list:
    """The freshness exempt set must be exactly the artifacts ``run_evidence.sh`` does not write.

    Round 8 found the set justified by a rationale that also described two files it does *not* exempt, and an
    exempt file that the sweep in fact regenerates. Stating the rule mechanically means it can be checked
    instead of argued: grep the sweep for each name.
    """
    script = DOC / "logs/run_evidence.sh"
    if not script.is_file():
        return []
    body = script.read_text()
    problems = []
    for name in sorted(EXEMPT_FROM_FRESHNESS):
        # commit_record/source_manifest/contract/triage are hand-written or written by the sweep's own
        # bookkeeping; only the measurement artifacts are interesting here.
        if not name.startswith("ab_"):
            continue
        if name in body:
            problems.append(
                f"FRESHNESS-EXEMPTION-WRONG  {name} is exempt from the freshness rule, but "
                f"logs/run_evidence.sh regenerates it - so its mtime is meaningful and it should be checked"
            )
    # The other half of the biconditional: an `ab_*` artifact the sweep does NOT write must be exempt, or
    # `check_freshness` measures its mtime against sources that were never used to produce it. Round 9 found
    # this loop present but empty - it matched the sweep's writes and then did nothing with them.
    written = {m.group(1) for m in re.finditer(r'"\$LOGS/(ab_[a-z0-9_]+\.txt)"', body)}
    for artifact in sorted((DOC / "logs").glob("ab_*.txt")):
        if artifact.name not in written and artifact.name not in EXEMPT_FROM_FRESHNESS:
            problems.append(
                f"FRESHNESS-EXEMPTION-MISSING  logs/{artifact.name} is not written by logs/run_evidence.sh "
                f"and is not in EXEMPT_FROM_FRESHNESS, so its mtime is checked against sources that did not "
                f"produce it"
            )
    return problems


#: Spelled-out numerals the documents actually use, so a claim written in words is checked like a digit.
#: Deliberately small: the point is to cover the compounding argument's phrasing, not to build a parser.
NUMERALS = {
    "eight": 8,
    "sixteen": 16,
    "thirty-nine": 39,
    "forty": 40,
    "forty-seven": 47,
    "forty-eight": 48,
    "two-hundred-and-fifty-six": 256,
}

#: ``(pattern, fact)``: wherever a document makes this claim, the captured number must equal that fact from
#: ``logs/model_facts.txt``. Patterns are deliberately narrow — each one is a phrasing the documents use to
#: state a checkpoint shape, and a capture that is not a number at all is skipped rather than guessed at.
FACT_CLAIMS = [
    (r"([\w-]+)-layer stack", "num_hidden_layers"),
    (r"([\w-]+)-layer PCC", "num_hidden_layers"),
    (r"one layer of ([\w-]+)", "num_hidden_layers"),
    (r"bet on the other ([\w-]+)", "num_layers_minus_one"),
    (r"([\w-]+) routed experts", "num_experts"),
    (r"top-(\d+) (?:experts|routing|routed)", "num_experts_per_tok"),
    (r"([\w-]+) experts per token", "num_experts_per_tok"),
]


#: Comparative magnitudes written as words. `audit_figures.py` matches numerals, so "nearly three times slower"
#: is invisible to it — and that blind spot produced a finding in three consecutive review rounds (18, 19 and 20),
#: each time a phrase that had been true of an *older* artifact and was never re-derived after the artifact moved.
#: The instances are cheap to fix; the class is not, because a magnitude in prose has no generator.
#:
#: This closes the half that matters most: the three SOURCE files, where README §1 already states the invariant
#: that no run-varying figure belongs, because a comment cannot be regenerated by a sweep. A ratio is a
#: run-varying figure whether it is spelled with a digit or a word.
MAGNITUDE_WORDS = re.compile(
    r"\b(?:twice|thrice|half|a third|two|three|four|five|six|seven|eight|nine|ten)\s+"
    r"(?:times\s+)?(?:as\s+)?(?:fast|slow|faster|slower|expensive|cheaper|cheap)\b",
    re.IGNORECASE,
)


def check_source_magnitude_words() -> list:
    """No spelled-out performance ratio in the implementation or its tests.

    README §1 promises that `tt/optimized_decoder.py` and its tests quote no run-varying absolute timing, and the
    figure audit enforces that for numerals. A ratio spelled in words is the same claim in a form the audit cannot
    see, and the stage has now broken and repaired that invariant three rounds running. Documents may carry a
    ratio - they are regenerated and audited beside their artifacts - but a source comment may not.
    """
    problems = []
    for source in SOURCES:
        if not source.is_file():
            continue
        for match in MAGNITUDE_WORDS.finditer(source.read_text()):
            problems.append(
                f'SOURCE-MAGNITUDE-WORD  {source.name}: "{match.group(0)}" is a run-varying ratio spelled as a '
                f"word, which no sweep regenerates and no figure check can see - state it in the work log beside "
                f"its artifact, or make the argument without the ratio"
            )
    return problems


#: Words a magnitude claim may be spelled with, beyond a plain numeral. "half a percent" and "about a percent"
#: differ by a factor of two and read almost identically, which is exactly how round 20's repair of one bullet
#: introduced a two-fold error into another.
CLAIM_WORDS = {"half": 0.5, "a": 1.0, "one": 1.0, "two": 2.0, "three": 3.0, "four": 4.0, "five": 5.0}

#: A magnitude claim in a source comment: "by ~12 %", "by about 2 %", "by half a percent", "by 47.3 µs".
#: Microseconds are covered as well as percentages — round 22 pointed out that an absolute op-level figure is
#: exactly as run-varying as a ratio, and the ladder's own rows moved by microseconds between sweeps.
CLAIM_PERCENT = re.compile(
    r"\bby\s+(?:about\s+|around\s+|roughly\s+|under\s+|over\s+|~)?(?P<value>\d+(?:\.\d+)?|"
    + "|".join(CLAIM_WORDS)
    + r")\s*(?:a\s+)?(?:%|percent|µs|us\b|microsecond)",
    re.IGNORECASE,
)

#: Which rectangle a bullet says won, taken from the first verb phrase in the bullet — later sentences routinely
#: mention the *other* orientation to say where it does not apply.
CLAIM_WINNER = re.compile(
    r"\bthe\s+\*?(?P<who>column|row)\*?\s+(?:wins|is\s+ahead|leads|is\s+never\s+behind)\b", re.IGNORECASE
)

#: `[ladder <active>/<role> ...]` — the generated-ladder rows a source bullet claims to be describing.
CLAIM_TAG = re.compile(r"\[ladder\s+(?P<rows>\d+/\w+(?:\s+\d+/\w+)*)\]")


def _orientation_ladder() -> dict:
    """The generated orientation ladder in `work_log.md`, as ``(active, role) -> (winner, gap_percent)``.

    The block is generated from ``logs/probe_sparse_matmul.txt`` by ``logs/make_readme.py`` and
    ``check_generators`` proves it still reproduces from that artifact, so reading it here is a chain back to
    the measurement rather than a second hand-maintained copy of it.
    """
    body = (DOC / "work_log.md").read_text(errors="replace")
    block = re.search(r"<!-- generated:orientation-ladder -->(.*?)<!-- /generated:orientation-ladder -->", body, re.S)
    if not block:
        return {}
    ladder = {}
    for line in block.group(1).splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 5 or not cells[0][:1].isdigit():
            continue
        active = int(re.match(r"(\d+)", cells[0]).group(1))
        role = cells[1].replace("/", "_")
        times = [float(m) for m in re.findall(r"([\d.]+) µs", f"{cells[2]} {cells[3]}")]
        if len(times) != 2:
            continue
        decisive = re.search(r"\*\*(column|row)\*\* wins by ([\d.]+) µs", cells[4])
        # A row whose two rectangles land inside the measured spread is a *non-result*, not a missing row, and
        # it has to be carried as one: the 64-active `gate_up` point crossed that line between two runs of the
        # same sweep (2.2 µs beyond a ±0.8 µs spread, then 0.3 µs inside a ±3.9 µs one). Dropping it here would
        # have made a marginal measurement look like a typo in the tag that names it.
        nominal = re.search(r"(column|row) nominally ahead, inside the", cells[4])
        if decisive:
            ladder[(active, role)] = (decisive.group(1), float(decisive.group(2)) / min(times) * 100.0)
        elif nominal:
            ladder[(active, role)] = (nominal.group(1), None)
    return ladder


def check_orientation_claims() -> list:
    """Every tagged orientation claim in a source comment must match the ladder rows it names.

    ``check_source_magnitude_words`` bans a *ratio* spelled as a word, but it matches on "twice as slow"-shaped
    phrasings and cannot see "wins by about a percent" — which is how a two-fold overstatement of the `down`
    orientation gap shipped in-tree at zero audit problems for a full round.

    The first version of this check tried to keep the magnitudes and verify them. Two consecutive sweeps then
    falsified three different bullets without a line of shipped code changing: `162/gate_up` moved 1.9 % -> 1.5 %,
    and the `64/gate_up` point crossed the spread boundary in both directions. That is not drift to be corrected,
    it is the measurement's own resolution — and a comment cannot track it, because no sweep regenerates a
    comment. So the rule is now the one the round-21 reviewer proposed: a tagged bullet states a **direction**,
    which is stable, and cites the generated ladder for the **magnitude**, which is not. Directions are still
    checked against the artifact here, so a sign error is caught the way round 20's was.
    """
    ladder = _orientation_ladder()
    if not ladder:
        return ["ORIENTATION-LADDER-MISSING  work_log.md has no generated:orientation-ladder block to check against"]
    problems = []
    for source in SOURCES:
        if not source.is_file():
            continue
        # A bullet is "# * ..." plus its "#   ..." continuations, so a claim keeps the rows it was written beside.
        for bullet in re.findall(r"^[ \t]*#[ \t]*\*[ \t].*(?:\n[ \t]*#[ \t]{2,}(?!\*).*)*", source.read_text(), re.M):
            tag = CLAIM_TAG.search(bullet)
            if not tag:
                # The gate would otherwise be opt-in: round 22 showed that an *untagged* bullet claiming
                # "the column wins by ~12 %" passes the whole audit, because two-digit integers are exempt
                # wholesale and this check only looked at tagged bullets. Any bullet making an orientation
                # claim has to name the rows it is claiming about.
                orphan = CLAIM_WINNER.search(" ".join(line.lstrip(" \t#") for line in bullet.splitlines()))
                if orphan:
                    problems.append(
                        f'ORIENTATION-CLAIM-UNTAGGED  {source.name}: "{orphan.group(0)}" makes an orientation '
                        f"claim with no [ladder <active>/<role>] tag, so no artifact row backs it"
                    )
                continue
            text = " ".join(line.lstrip(" \t#") for line in bullet.splitlines())
            rows = []
            for token in tag.group("rows").split():
                active, _, role = token.partition("/")
                key = (int(active), role)
                if key not in ladder:
                    problems.append(
                        f"ORIENTATION-CLAIM-ROW  {source.name}: [ladder {token}] names a row the generated "
                        f"ladder does not have ({sorted(ladder)})"
                    )
                else:
                    rows.append((token, *ladder[key]))
            if not rows:
                continue
            claimed_winner = CLAIM_WINNER.search(text)
            claimed_percent = CLAIM_PERCENT.search(text)
            # No magnitude, at all. This is the rule that stops the treadmill: a percentage here is a
            # run-varying figure with no generator behind it, so it is wrong as soon as the sweep is re-run.
            if claimed_percent:
                problems.append(
                    f'ORIENTATION-CLAIM-MAGNITUDE  {source.name}: "{claimed_percent.group(0)}" states a '
                    f"run-varying magnitude a source comment cannot keep true - state the direction here and "
                    f"leave the figure to the generated ladder this bullet already cites"
                )
            if not claimed_winner:
                problems.append(
                    f'ORIENTATION-CLAIM-UNREADABLE  {source.name}: "{text[:90]}..." carries a [ladder] tag but '
                    f"states no `the <column|row> wins/leads/is never behind` direction for the audit to check"
                )
                continue
            who = claimed_winner.group("who").lower()
            for token, winner, percent in rows:
                if who != winner:
                    # `percent is None` means the two rectangles landed inside the run's spread. The direction
                    # is then only nominal, but a bullet naming the *opposite* rectangle still contradicts the
                    # only measurement there is.
                    where = "does" if percent is not None else "is nominally ahead, inside the run's spread"
                    problems.append(
                        f'ORIENTATION-CLAIM-WINNER  {source.name}: "{text[:70]}..." says the {who} leads at '
                        f"[ladder {token}], the generated ladder says the {winner} {where}"
                    )
    return problems


def check_top_line_item() -> list:
    """A document naming *the largest* op-to-op line item must name the one the capture actually has.

    This closes the defect round 22 found, which had survived twenty-one review rounds at zero audit problems.
    §7's itemisation table is generated from ``perf_summary.json``, but the sentence announcing which op code
    tops it was hard-coded — *inside* the generated block, where ``make_readme.py --check`` regenerates it from
    itself and can never see that it has gone stale. It named ``TypecastDeviceOperation`` at 7 launches a step
    through every re-capture that demoted it to fourth at 4 launches, pointing the next stage at 9 % of the
    dispatch gap instead of the 46 % sitting above it.

    The generated sentence is computed now, so this check guards the *hand-written* prose that cites it: any
    claim that some ``…DeviceOperation`` is the largest line item is matched against the top row of every layer
    kind in the summary.
    """
    path = DOC / "tracy/perf_summary.json"
    if not path.is_file():
        return []
    import json as _json

    data = _json.loads(path.read_text())
    tops = set()
    for kind, payload in data.items():
        if isinstance(payload, dict) and payload.get("op_to_op_gaps", {}).get("largest"):
            tops.add(payload["op_to_op_gaps"]["largest"][0]["op_code"])
    if not tops:
        return []
    problems = []
    claim = re.compile(r"`(?P<op>\w*DeviceOperation)`[^.]{0,200}?\blargest\b[^.]{0,80}?\bline item\b", re.S)
    reverse = re.compile(r"\blargest\b[^.]{0,80}?\bline item\b[^.]{0,200}?`(?P<op>\w*DeviceOperation)`", re.S)
    for doc in DOCS:
        if not doc.is_file() or doc.suffix != ".md":
            continue
        text = doc.read_text(errors="replace")
        for pattern in (claim, reverse):
            for match in pattern.finditer(text):
                if match.group("op") not in tops:
                    problems.append(
                        f"TOP-LINE-ITEM-WRONG  {doc.relative_to(REPO)}: calls `{match.group('op')}` the largest "
                        f"op-to-op line item; the capture's largest is {sorted(tops)} "
                        f"(tracy/perf_summary.json)"
                    )
    return problems


def check_model_facts() -> list:
    """Documents must not contradict the checkpoint's own shape constants.

    The class of defect this closes: ``ALLOWED_INT`` exempts every two-digit integer wholesale, because a
    document legitimately quotes dozens of shape and config constants and sourcing each one against a log
    would be noise. That exemption is why five documents could call this a 48-layer model — including the
    prose of a *generated* block and a shipped source comment — while the checkpoint has 40 layers and the
    figure was the denominator of a policy decision (README §4.3). Spelled-out numerals were invisible for a
    second reason: they are not numbers.

    So the shapes come from ``logs/model_facts.py`` as a committed artifact, and the phrasings the documents
    use to state them are matched against it, in words or digits.
    """
    facts_path = DOC / "logs/model_facts.txt"
    if not facts_path.is_file():
        return ["MODEL-FACTS-MISSING  logs/model_facts.txt is absent; run logs/model_facts.py"]
    facts = {m.group(1): int(m.group(2)) for m in re.finditer(r"^FACT (\w+)=(\d+)$", facts_path.read_text(), re.M)}
    missing = [name for _, name in FACT_CLAIMS if name not in facts]
    if missing:
        return [f"MODEL-FACTS-INCOMPLETE  logs/model_facts.txt has no {sorted(set(missing))}"]
    problems = []
    for doc in DOCS:
        if not doc.is_file() or doc.name == "audit_figures.py":
            continue
        text = doc.read_text()
        for pattern, fact in FACT_CLAIMS:
            for match in re.finditer(pattern, text):
                token = match.group(1).lower()
                value = NUMERALS.get(token)
                if value is None:
                    if not token.isdigit():
                        continue  # "the other rectangle", "top-k": a phrase, not a claim about a shape
                    value = int(token)
                if value != facts[fact]:
                    problems.append(
                        f'MODEL-FACT-WRONG  {doc.relative_to(REPO)}: "{match.group(0)}" says {value}, '
                        f"the checkpoint's "
                        f"{fact} is {facts[fact]} (logs/model_facts.txt)"
                    )
    return problems


def check_sparse_block_rule() -> list:
    """The output-block rule the generated sparse table pins must be the rule the layer logged.

    Round 10's finding: `make_readme.block_sparse_search` looked the shipped row up by (cores, in0_block_w,
    per_core_N) and took `min()`, while the probe sweeps `out_block_w` and `sub_w` as independent axes - so at
    one point it reported a *faster* geometry than the layer builds, and the mirror checks could not see it
    because they mirror the core rule and not the block rule. Five consecutive rounds found that one lookup
    under-constrained by exactly one axis, which is the argument for checking the rule rather than the table.

    This checks it against the layer's own record instead of against the implementation's text: the suite log
    prints every sparse program config the layer actually built (``... sparse matmuls ... per_core_N=N
    out_block_w=W sub_w=S``), so the two invariants - ``out_block_w == per_core_N`` and
    ``out_subblock_w == largest divisor of per_core_N at most 8`` - are asserted on measured behaviour. If the
    layer's rule changes, the generated table's pins become wrong and this fails.
    """
    log = artifact_path(DOC / "logs/pytest_full_suite.txt")
    if not exists(DOC / "logs/pytest_full_suite.txt"):
        return ["MISSING-ARTIFACT  logs/pytest_full_suite.txt (needed for the sparse block rule)"]
    body = read_blob(log)
    # Every triple in the log, not one per line: a single line lists several configs, and the dense matmul
    # lines carry the same three fields under the same rule, so scanning all of them widens the check.
    seen = re.findall(r"per_core_N=(\d+) out_block_w=(\d+) sub_w=(\d+)", body)
    if not seen:
        return ["SPARSE-RULE-UNRECORDED  the suite log records no sparse program config to check the rule on"]
    problems = []
    for pcn, obw, sub in {tuple(map(int, s)) for s in seen}:
        expect_sub = max((d for d in range(min(8, pcn), 0, -1) if pcn % d == 0), default=1)
        if obw != pcn or sub != expect_sub:
            problems.append(
                f"SPARSE-BLOCK-RULE-DRIFT  the suite log records a sparse config with per_core_N={pcn}, "
                f"out_block_w={obw}, sub_w={sub}; the rule the generated table pins is out_block_w=per_core_N "
                f"and sub_w={expect_sub}, so README §5.4's shipped column describes a geometry the layer does "
                f"not build"
            )
    return problems


def check_mirrored_constants() -> list:
    """``make_readme.py`` mirrors a few implementation rules; assert they still agree with the code.

    ``block_sparse_search`` restates the routed core-count rule and the grid orientation, and
    ``block_decode_search`` restates how a core target becomes a realised grid. Round 6 pointed out that
    both drift silently if the layer changes — the generator would keep producing a confident table about a
    geometry the layer no longer builds.

    Four things are checked, and the list is exhaustive on purpose because rounds 8 and 9 both found this
    docstring describing checks that did not exist: the four sparse constants, the two named mirrors of them
    in ``make_readme.py``, which grid axis each side fills first, and — by behaviour rather than by text —
    that the generator's copy of ``_largest_divisor_at_most`` agrees with the implementation's on every
    (Nt, target) pair the layer can reach. Round 9 also fixed the function re-binding ``problems`` after the
    first block of comparisons, which made every finding in it an ``UnboundLocalError`` instead.

    The constants are read out of the source with ``ast``, not imported: importing the implementation pulls
    in ttnn, which is slow, prints allocator noise, and has no business running inside a documentation
    audit.
    """
    import ast

    source = ROOT / "tt/optimized_decoder.py"
    if not source.is_file():
        return ["MIRROR-SOURCE-MISSING  cannot read the implementation to check mirrored rules"]
    try:
        tree = ast.parse(source.read_text())
    except SyntaxError as exc:
        return [f"MIRROR-PARSE-FAILED  {exc}"]
    found: dict = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
            if name in {
                "SPARSE_CORES_PER_ACTIVE",
                "SPARSE_MIN_CORES",
                "SPARSE_MAX_CORES",
                "SPARSE_GATE_UP_IN0_BLOCK_W",
            }:
                try:
                    found[name] = ast.literal_eval(node.value)
                except ValueError:
                    pass
    #: What make_readme.block_sparse_search assumes. Keep in step with that function.
    expected = {
        "SPARSE_CORES_PER_ACTIVE": {"gate_up": 2, "down": 4},
        "SPARSE_MIN_CORES": 8,
        "SPARSE_MAX_CORES": 32,
        # The generated sparse table picks which phase's `in0_block_w` applies from the realised core count.
        # That rule is only meaningful while the cap actually differs between the two, so the *shape* of this
        # constant is mirrored, not just its presence: round 7 found the table reporting the decode cap on a
        # prefill row precisely because it assumed a single cap after round 6 had made it two.
        "SPARSE_GATE_UP_IN0_BLOCK_W": {False: 32, True: 64},
    }
    # `make_readme.py` keeps its own copies of two of these plus the routed output widths, because it must
    # reproduce the layer's target->realised core reduction without importing ttnn. Round 8 found the
    # docstrings claiming this function compared them when it only ever read the implementation. It reads
    # both now.
    problems: list[str] = []
    mirrors = ROOT / "doc/optimized_decoder/logs/make_readme.py"
    if mirrors.is_file():
        text = mirrors.read_text()
        for name, want in (("SPARSE_MIN_CORES_MIRROR", found.get("SPARSE_MIN_CORES")),):
            m = re.search(rf"^{name} = (\d+)", text, re.M)
            if not m:
                problems.append(f"MIRRORED-RULE-MISSING  {name} not found in logs/make_readme.py")
            elif want is not None and int(m.group(1)) != want:
                problems.append(
                    f"MIRRORED-RULE-DRIFT  logs/make_readme.py {name} is {m.group(1)}, the implementation's "
                    f"SPARSE_MIN_CORES is {want}"
                )
        m = re.search(r"SPARSE_N_TILES_MIRROR = \{([^}]*)\}", text)
        want_tiles = {"gate_up": 2 * 512 // 32, "down": 2048 // 32}
        if not m:
            problems.append("MIRRORED-RULE-MISSING  SPARSE_N_TILES_MIRROR not found in logs/make_readme.py")
        else:
            got = {}
            for pair in m.group(1).split(","):
                if ":" in pair:
                    k, _, v = pair.partition(":")
                    try:
                        got[k.strip().strip("\"'")] = int(eval(v, {}, {}))  # noqa: S307
                    except Exception:  # noqa: BLE001
                        pass
            if got != want_tiles:
                problems.append(
                    f"MIRRORED-RULE-DRIFT  logs/make_readme.py SPARSE_N_TILES_MIRROR is {got!r}, the routed "
                    f"output widths give {want_tiles!r}"
                )
    # The grid orientation itself: `make_readme.shipped_grid` fills the y axis first and the implementation
    # must still do the same. Round 9 measured the transposed rectangle end to end and rejected it
    # (`logs/ab_sdpa_decode_grid.txt`), so the two are expected to agree on the column form — but the whole
    # point of a mirror check is that a later change to either side is caught rather than assumed.
    if mirrors.is_file():
        gen_fills_y = re.search(r"def shipped_grid\(cores\):\s*\n\s*cy = min\(cores, 10\)", mirrors.read_text())
        impl_fills_y = re.search(
            r"cy = min\(cores, int\(grid\.y\) if grid is not None else cores\)", source.read_text()
        )
        if bool(gen_fills_y) != bool(impl_fills_y):
            problems.append(
                "MIRRORED-RULE-DRIFT  the sparse grid orientation differs between tt/optimized_decoder.py "
                f"(fills y first: {bool(impl_fills_y)}) and logs/make_readme.shipped_grid "
                f"(fills y first: {bool(gen_fills_y)})"
            )
    # The target->realised core reduction: `make_readme.py` keeps its own `_largest_divisor_at_most` so it can
    # reproduce the layer's geometry without importing ttnn, and round 9 pointed out that nothing tied the two
    # together even though this docstring said so. Both are pure integer functions, so the mirror is checked by
    # *behaviour*: each definition is extracted with `ast`, exec'd alone in an empty namespace — no ttnn, no
    # module import — and the two are compared over every (Nt, target) pair the layer can reach.
    if mirrors.is_file():

        def _extract(text: str, fn: str):
            for node in ast.parse(text).body:
                if isinstance(node, ast.FunctionDef) and node.name == fn:
                    ns: dict = {}
                    exec(compile(ast.Module(body=[node], type_ignores=[]), "<mirror>", "exec"), ns)  # noqa: S102
                    return ns[fn]
            return None

        impl_fn = _extract(source.read_text(), "_largest_divisor_at_most")
        gen_fn = _extract(mirrors.read_text(), "_largest_divisor_at_most")
        if impl_fn is None or gen_fn is None:
            problems.append(
                "MIRRORED-RULE-MISSING  _largest_divisor_at_most not found in "
                f"{'tt/optimized_decoder.py' if impl_fn is None else 'logs/make_readme.py'}"
            )
        else:
            disagree = [
                (n, cap)
                for n in (32, 64)  # the routed output widths in tiles
                for cap in range(1, 129)
                if impl_fn(n, cap) != gen_fn(n, cap)
            ]
            if disagree:
                n, cap = disagree[0]
                problems.append(
                    f"MIRRORED-RULE-DRIFT  logs/make_readme._largest_divisor_at_most disagrees with the "
                    f"implementation on {len(disagree)} (Nt, target) pairs, first ({n}, {cap}): "
                    f"{gen_fn(n, cap)} vs {impl_fn(n, cap)}"
                )
    for name, want in expected.items():
        got = found.get(name)
        if got is None:
            problems.append(f"MIRRORED-RULE-MISSING  {name} not found in tt/optimized_decoder.py")
        elif name == "SPARSE_MIN_CORES" and got != 8:
            problems.append(
                f"MIRRORED-RULE-DRIFT  make_readme.SPARSE_MIN_CORES_MIRROR is 8, the implementation says {got!r}"
            )
        elif got != want:
            problems.append(
                f"MIRRORED-RULE-DRIFT  make_readme.block_sparse_search mirrors {name} as {want!r}, the "
                f"implementation says {got!r}"
            )
    return problems


#: Artifacts the freshness rule does not apply to, and why.
#:
#: * ``commit_record.txt`` is written by hand after the commit, and ``source_manifest.txt`` is the
#:   freshness evidence itself.
#: * ``context_contract.json`` is a document that is also evidence; its figures are audited.
#: * ``triage/`` is a capture of a *hardware incident* that a re-run must not reproduce on purpose.
#: * The four ``ab_*.txt`` below are **one-off decision records** that ``run_evidence.sh`` does not
#:   regenerate. The distinction is not "needs a different constant" — round 8 pointed out that
#:   ``ab_norm_shard_width.txt`` varies a class attribute exactly as the two *regenerated* A/Bs do, so that
#:   rationale described both groups. The actual rule is simpler and mechanical: **a file is exempt if and
#:   only if no phase of ``run_evidence.sh`` writes it.** Two of these four vary a constant, one varies a
#:   dtype on one multiply and one varies a k-chunk the layer must not ship; what they have in common is
#:   that nobody automated them, so their level belongs to the revision that produced them. They are A/B *pairs* measured back to back in one process, so what they establish is the
#:   sign and size of a **difference**, which does not go stale when unrelated code changes; their absolute
#:   level belongs to the revision that produced them, and the shipped default's absolute level is
#:   re-measured end to end on every run in ``ab_fused_vs_optimized.txt``. Documents quoting them must
#:   quote the pair, not the level.
#:
#: ``ab_norm_shard_cores.txt`` and ``ab_gate_up_in0_block_w.txt`` are deliberately NOT here: both swap a
#: constant at runtime rather than needing a variant of the implementation, so ``run_evidence.sh``
#: regenerates them and the freshness rule applies. Round 7 caught the first of the two exempted under a
#: rationale that did not describe it.
EXEMPT_FROM_FRESHNESS = {
    "commit_record.txt",
    "context_contract.json",
    "source_manifest.txt",
    "tt-triage.txt",
    "triage-summary.txt",
    "ab_gdn_out_activation.txt",
    "ab_norm_shard_width.txt",
    "ab_state_l1.txt",
    "ab_sdpa_decode_contract.txt",
}


def check_freshness() -> list:
    """Every artifact must be newer than the code it measures.

    The guard for the one failure mode a figure audit cannot see: a source edit landing after the
    evidence run, so that every committed number describes a revision that is not the one being
    shipped. Files written by hand after the run, and the preceding stages' evidence, are exempt.

    The sha256 manifest is the primary guarantee and this mtime pass is a second, independent one. Round 5's
    fix made the hash *authoritative* by returning early whenever it matched — and round 8 pointed out that
    this switched the mtime pass off in every passing tree, i.e. always. It matters because the two catch
    different things: the manifest proves the artifacts were produced by these bytes, but a sweep that dies
    part-way (``run_evidence.sh`` writes the manifest in step 0 and runs under ``set -e``) leaves a
    *matching* manifest beside artifacts from the previous revision, and only an mtime comparison sees that.
    So the pass runs unconditionally now.

    Round 9 then found the same hole one step further in: round 8 kept the pass running but *downgraded* a
    stale artifact to an advisory note whenever the manifest matched — and the manifest matches in every tree
    that passes, so the pass still could not fail, and the exact scenario the docstring above names is a
    manifest-matching one. A stale mtime is a **problem** now, with no manifest escape: the manifest says the
    sources were not edited since they were hashed, which is a different statement from "this artifact came
    out of the current sweep". The cost is that touching a source without changing its bytes fails the gate
    until the sweep is re-run or the mtime restored, which is the correct way round.

    One consequence is still handled rather than papered over: a ``git archive`` extraction stamps every file
    with the commit time, so ordering there is meaningless — the run is skipped when every artifact and
    source share one mtime, which is the archive signature.
    """
    problems = []
    newest = max(((p.stat().st_mtime, p) for p in SOURCES if p.is_file()), default=None)
    if newest is None:
        return ["MISSING-SOURCE  no implementation file found to check freshness against"]
    stamp, source = newest
    # A `git archive` extraction gives every file the commit's timestamp, which makes ordering vacuous.
    # Detect that signature and skip rather than report meaningless results: if no artifact is even one
    # second older than the newest source AND none is newer, the tree has a single uniform mtime.
    stamps = {
        artifact_path(p).stat().st_mtime
        for p in ARTIFACTS + PER_OP_REPORTS
        if exists(p) and p.name not in EXEMPT_FROM_FRESHNESS
    }
    if len(stamps | {stamp}) <= 1:
        return []
    for path in ARTIFACTS + PER_OP_REPORTS:
        exempt = path.name in EXEMPT_FROM_FRESHNESS or any(
            part in {"fused_decoder", "functional_decoder"} for part in path.parts
        )
        if exempt or not exists(path):
            continue
        if artifact_path(path).stat().st_mtime < stamp:
            problems.append(
                f"STALE-ARTIFACT  {path.name} predates {source.name} - re-run logs/run_evidence.sh, or "
                f"restore the mtime if the source was only touched"
            )
    return problems


def check_suite_log_complete() -> list:
    """The committed suite and watcher logs must record runs that *finished*.

    The fused stage shipped a suite log that had been stopped mid-test once, while every figure
    generated from it looked right. A log with no pytest summary line cannot back any figure.
    """
    problems = []
    for name in ("logs/pytest_full_suite.txt", "logs/watcher_pytest.txt"):
        body = read_blob(DOC / name)
        if body is None:
            continue  # the missing-artifact pass reports it
        # ANSI-stripped first: pytest colourises its summary when something in the environment forces colour
        # even with stdout redirected, and round 13's sweep produced exactly that - a log whose summary line
        # begins with an escape sequence rather than `=`, which this regex missed and reported as an unfinished
        # run. The sweep strips the codes when writing now; this strips them when reading, so a log captured by
        # hand from a terminal is checkable too.
        plain = re.sub(r"\x1b\[[0-9;]*m", "", body)
        if not [ln for ln in plain.splitlines() if re.match(r"=+ .*(passed|failed)", ln)]:
            problems.append(
                f"INCOMPLETE-LOG  {name} has no pytest summary line: the run it records did not "
                f"finish, so no figure generated from it is backed by a completed suite"
            )
    return problems


#: Figure classes the self-test measures, as (label, generator-expression over `rnd`).
SELFTEST_CLASSES = [
    ("three-decimal ms in 0..10", "f'{rnd.uniform(0, 10):.3f}'"),
    ("one-decimal us in 1..999", "f'{rnd.uniform(1, 999):.1f}'"),
    ("six-decimal PCC in 0.99..1", "f'{rnd.uniform(0.99, 1):.6f}'"),
    ("7-10 digit byte counts", "str(rnd.randint(10 ** 6, 10 ** 10))"),
    ("three-digit integers", "str(rnd.randint(100, 999))"),
    # Deliberately included although ALLOWED_INT exempts this whole range: the rate makes the size of that
    # exemption visible instead of implicit. A two-digit integer here is almost always a core count, a tile
    # count or a section number — but a two-digit MICROSECOND figure is not, and the audit cannot tell them
    # apart. That limit belongs in the artifact rather than in a reader's head.
    ("two-digit integers (ALLOWED_INT exempts 12-99 wholesale)", "str(rnd.randint(12, 99))"),
]
SELFTEST_SAMPLES = 2000
SELFTEST_SEED = 7


def selftest() -> str:
    """Measure how often ``sourced()`` says yes to an arbitrary value of each figure class.

    This is the audit auditing itself, and it exists because round 5 of the stage review found the first
    version of this file admitting ~4 in 5 arbitrary millisecond values — a fact about the *check*, which
    no amount of running the check could reveal. Committing the rate as an artifact means a later change to
    the matching rules that quietly weakens them shows up as a number moving, and it means the rates quoted
    in this docstring and in the README are sourced rather than asserted.
    """
    import random

    # NOT measuring a pool that contains the selftest's own previous output: it is a list of numbers, so
    # including it makes the experiment self-referential and it never converges — round 6 measured exactly
    # that, three consecutive runs producing three different files. `audit_selftest.txt` is therefore out of
    # ARTIFACTS entirely, which also makes this reproducible enough for `check_generators` to diff.
    # `commit_record.txt` is excluded: it is a hand-written checkpoint note, not measurement evidence, and
    # it is written AFTER the sweep — it names the commit that contains it. Leaving it in made this
    # artifact's own header depend on a file edited after it was generated, so the committed selftest could
    # never match its regeneration. (Caught by the committed-tree run of this audit, which is what that run
    # is for.)
    blobs = {path: body for path, body in load(ARTIFACTS).items() if path.name != "commit_record.txt"}
    tokens = measured_tokens(blobs) | derived_from_artifacts(blobs)
    rnd = random.Random(SELFTEST_SEED)
    lines = [
        "# How often audit_figures.sourced() says yes to an ARBITRARY value of each figure class.",
        "# Lower is stronger. Written by `audit_figures.py --selftest`; a rate that rises means the",
        "# matching rules got weaker. Seeded, so it is reproducible.",
        # Deliberately NOT a byte count: it is incidental to what this measures and it moves whenever any
        # artifact gains a line, which made the file fail its own reproducibility check.
        f"# pool: {len(blobs)} artifacts, {len(tokens)} labelled tokens",
    ]
    for label, expression in SELFTEST_CLASSES:
        # Counts an ACCEPTANCE, which is what the gate actually does: sourced OR blanket-exempted. Without
        # the exemptions in the predicate the two-digit row would read 0 % while every such figure passes.
        hits = sum(
            1
            for _ in range(SELFTEST_SAMPLES)
            for value in [eval(expression, {"rnd": rnd})]  # noqa: S307
            if value in ALLOWED or value in ALLOWED_INT or sourced(value, tokens)
        )
        lines.append(f"SELFTEST class={label!r} hits={hits} of={SELFTEST_SAMPLES} rate={hits / SELFTEST_SAMPLES:.4f}")
    return "\n".join(lines) + "\n"


def main() -> int:
    if "--selftest" in sys.argv:
        text = selftest()
        (DOC / "logs/audit_selftest.txt").write_text(text)
        print(text, end="")
        return 0
    all_blobs = load(ARTIFACTS)
    all_tokens = measured_tokens(all_blobs) | derived_from_artifacts(all_blobs)
    #: Every labelled claim ("109 passed") the LABELLED rules actually matched. Reported, because a pass
    #: that matches nothing is not coverage: round 6 found these rules dead for months because they ran on
    #: text whose markdown had already been stripped. Today the count is legitimately low — every such
    #: claim in the README is inside a generated block, and those are checked by `make_readme.py --check`
    #: instead — but the number has to be visible for that to be a conclusion rather than an assumption.
    labelled_checked: list = []
    problems = [f"MISSING-ARTIFACT  {p.relative_to(REPO)}" for p in ARTIFACTS + PER_OP_REPORTS if not exists(p)]
    problems += check_source_manifest()
    problems += check_suite_log_complete()
    problems += check_freshness()
    problems += check_freshness_exemptions()
    problems += check_model_facts()
    problems += check_source_magnitude_words()
    problems += check_orientation_claims()
    problems += check_top_line_item()
    problems += check_sparse_block_rule()
    problems += check_mirrored_constants()
    problems += check_generators()
    problems += check_derived(all_tokens)

    for doc in DOCS:
        if not doc.is_file():
            problems.append(f"MISSING-DOC  {doc}")
            continue
        # A document that is also an artifact must not source its own figures: that is circular, and it
        # would make the capability contract's numbers self-certifying now that it is audited.
        tokens = (
            all_tokens
            if doc not in all_blobs
            else measured_tokens({path: body for path, body in all_blobs.items() if path != doc})
        )
        body = doc.read_text(errors="replace")
        if doc == CONTRACT:
            # Only this stage's own section. The other stages' sections are their evidence's business,
            # and auditing them here would demand artifacts this stage does not own.
            import json as _json

            # ensure_ascii=False: with the default, "§4.8" is emitted as "\u00a74.8" and the section
            # stripper then leaves "74.8" behind as a phantom figure.
            body = _json.dumps(_json.loads(body).get("optimized_decoder", {}), indent=1, ensure_ascii=False)
        # Two texts: `text` has identifiers/sections/generated blocks stripped and is what the numeric
        # passes scan; `labelled_text` keeps the markdown, because the LABELLED rules match a value
        # TOGETHER WITH its label ("**109 passed**") and the strippers eat the markdown that surrounds it.
        # Round 6 found the LABELLED pass matching nothing at all across all 17 documents for that reason.
        labelled_text = GENERATED_BLOCK.sub(" ", body)

        # NOTE: the strippers run per paragraph below, not over the whole body, because `SECTION` removes the
        # `## N.` headings and the HISTORICAL rule needs to know which section a paragraph is in. Round 13's
        # first attempt at that rule searched the unstripped body with offsets taken from the stripped one, so it
        # silently never matched - a scoping check that cannot fire is the same defect class as the gates rounds
        # 5, 8, 10 and 12 found, one layer up.
        def strip(chunk: str) -> str:
            return IDENTIFIER.sub(" ", RULE_ID.sub(" ", SECTION.sub(" ", chunk)))

        scope_blobs = {path: b for path, b in all_blobs.items() if path != doc}
        # Ratios computed from the A/B artifact count as being "in" it: a paragraph that cites
        # ab_fused_vs_optimized.txt and quotes a speedup is citing correctly.
        scope_extra = derived_from_artifacts(scope_blobs)
        cache: dict = {}
        # `HISTORICAL` is admissible only in the sections that RECORD a superseded measurement: §3's
        # development ladder (rows measured on intermediate revisions of the code, which no artifact of the
        # shipped revision can contain) and §6's review rounds (what a round found and what replaced it).
        # Round 13 pointed out the check was file-level while this rationale is section-level, so a superseded
        # figure could be quoted as a live claim anywhere in the work log. Now it cannot.
        section = None

        # Paragraph by paragraph, so a figure can be checked against the artifact its own sentence cites
        # rather than against the whole pool. A paragraph that cites nothing is checked against the pool.
        for raw_paragraph in re.split(r"\n\s*\n", labelled_text):
            heading = None
            for match in re.finditer(r"(?m)^#{1,6}\s+(\d+)[.\s]", raw_paragraph):
                heading = match.group(1)
            if heading is not None:
                section = heading
            historical_ok = doc.name == "work_log.md" and section in HISTORICAL_SECTIONS
            paragraph = strip(raw_paragraph)
            scoped = scoped_tokens(paragraph, scope_blobs, cache)
            pool, where = (
                (scoped | scope_extra, "its cited artifact") if scoped is not None else (tokens, "any artifact")
            )
            for value in sorted(set(DECIMAL.findall(paragraph))):
                if value in ALLOWED or value in DERIVED or sourced(value, pool):
                    continue
                # A superseded figure may be quoted only where a document RECORDS that it was wrong,
                # which is work_log §6. Extending this to code comments was tried and reverted: it
                # immediately hid a live wrong claim ("1.07 % of the prefill window") in a generator,
                # because a generator's comments and its output prose are the same file.
                if value in HISTORICAL and historical_ok:
                    continue
                # A cited paragraph that fails may still be right against the pool; say which it is, so a
                # miscitation reads differently from an invented number.
                if scoped is not None and sourced(value, tokens):
                    problems.append(f"MISCITED  {doc.name}: {value} is not in the artifact this paragraph cites")
                else:
                    problems.append(f"UNSOURCED  {doc.name}: {value} (not in {where})")
            # Integers are only checked in the *documents*. In a source file or a generator an integer is
            # a shape, a tile count, a core count or a config constant - `2048`, `11`, `320`, `64` - and
            # requiring each to appear in a run log would mean exempting most of them by value, which
            # exempts real figures with the same digits. Decimals in code comments are almost always
            # measurements, and those are still checked, in every file.
            if doc in SOURCES or doc.suffix == ".py":
                continue
            for value in sorted(set(INTEGER.findall(paragraph))):
                if value in ALLOWED_INT or value in DERIVED or sourced(value, pool):
                    continue
                # A superseded figure may be quoted where a document RECORDS that it was wrong:
                # work_log §6, and the code comments that explain why a generator now derives a value.
                # Same rule as the decimal pass: only work_log.md, which is where a review finding gets
                # recorded. Round 6 found this branch still admitting `.py` documents, so a generator or a
                # probe could quote a superseded integer with no artifact behind it.
                if value in HISTORICAL and historical_ok:
                    continue
                if scoped is not None and sourced(value, tokens):
                    continue  # integers are too collision-prone to call a miscitation on
                problems.append(f"UNSOURCED-INT  {doc.name}: {value}")
        for pattern, template in LABELLED:
            for value in sorted(set(pattern.findall(labelled_text))):
                labelled_checked.append(f"{doc.name}: {value.strip()}")
                phrase = template.format(value.strip().replace(",", "").replace(" ", ""))
                if not phrase_in_artifacts(phrase, scope_blobs):
                    problems.append(f"UNSOURCED-LABEL  {doc.name}: {phrase!r}")

    for note in NOTES:
        print(note)
    for problem in problems:
        print(problem)
    print(
        f"checked {len(DOCS)} documents (including {len(SOURCES)} source files) against "
        f"{len(all_blobs)} artifacts, evaluated {len(DERIVED)} derived figures, re-ran the README "
        f"generator and both summary generators, and asserted every artifact is newer than the code "
        f"and produced by its recorded hash. Labelled claims matched outside generated blocks: "
        f"{len(labelled_checked)}. {len(NOTES)} note(s), {len(problems)} problem(s)"
    )
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
