include(sources.cmake)

add_library(ttnn_op_experimental_kda_recurrent_gated_delta_rule ${LIB_TYPE})
add_library(
    TTNN::Ops::Experimental::KDA::RecurrentGatedDeltaRule
    ALIAS ttnn_op_experimental_kda_recurrent_gated_delta_rule
)

tt_reuse_precompile_headers(ttnn_op_experimental_kda_recurrent_gated_delta_rule TT::CommonPCH)
TT_ENABLE_UNITY_BUILD(ttnn_op_experimental_kda_recurrent_gated_delta_rule)

file(GLOB_RECURSE kernels device/kernels/*.cpp)

target_sources(
    ttnn_op_experimental_kda_recurrent_gated_delta_rule
    PUBLIC
        FILE_SET api
        TYPE HEADERS
        BASE_DIRS ${FixmeOpAPIDir}
        FILES ${TTNN_OP_EXPERIMENTAL_KDA_RECURRENT_GATED_DELTA_RULE_API_HEADERS}
        FILE_SET kernels
        TYPE HEADERS
        BASE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}
        FILES ${kernels}
    PRIVATE
        ${TTNN_OP_EXPERIMENTAL_KDA_RECURRENT_GATED_DELTA_RULE_SRCS}
)

target_link_libraries(
    ttnn_op_experimental_kda_recurrent_gated_delta_rule
    PRIVATE
        TT::Metalium
        TTNN::Ops::Experimental::KDA::Common
    PUBLIC
        TTNN::Core
)

install(
    TARGETS
        ttnn_op_experimental_kda_recurrent_gated_delta_rule
    FILE_SET
    kernels
        DESTINATION
            ${CMAKE_INSTALL_LIBEXECDIR}/tt-metalium/ttnn/cpp/ttnn/operations/experimental/kda/recurrent_gated_delta_rule
        COMPONENT ttnn-runtime
)
install(
    TARGETS
        ttnn_op_experimental_kda_recurrent_gated_delta_rule
    FILE_SET
    api
        COMPONENT ttnn-dev
    LIBRARY
        COMPONENT tar
)

if(TARGET ttnn)
    target_sources(ttnn PRIVATE ${TTNN_OP_EXPERIMENTAL_KDA_RECURRENT_GATED_DELTA_RULE_NANOBIND_SRCS})
endif()
